#ifndef AS_OBJ_H_GENERATED_
#define AS_OBJ_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'qz' 'set_prop' */
extern void (*Z_qzZ_set_propZ_viii)(u32, u32, u32);
/* import: 'qz' 'new_number' */
extern u32 (*Z_qzZ_new_numberZ_ii)(u32);
/* import: 'qz' 'new_object' */
extern u32 (*Z_qzZ_new_objectZ_iv)(void);
/* import: 'qz' 'get_prop' */
extern u32 (*Z_qzZ_get_propZ_iii)(u32, u32);
/* import: 'qz' 'dump' */
extern void (*Z_qzZ_dumpZ_vi)(u32);

/* export: 'objbench' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_objbenchZ_ii))(u32);
/* export: 'memory' */
extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
#ifdef __cplusplus
}
#endif

#endif  /* AS_OBJ_H_GENERATED_ */
